### ISSUE TITLE
No longer Mx 9 compatible direct from Store

### ISSUE THREAD

**Issue by vvhhv** [ArjenLammers/library-logging#3]
Hi, thank you for the quick reaction to the patching. Unfortunately, the latest version can no longer be directly downloaded into a Mendix v9 project.

**Comment by ArjenLammers** [comment]
HI vvhhv,

Thanks for this issue.
It seems I selected the wrong framework version in the App Store.
You should be able to download it from your Studio Pro again.

Kind regards,
Arjen Lammers
