### ISSUE TITLE
SetRootLevel is fine to use in production

### ISSUE THREAD

**Issue by basi01** [ArjenLammers/library-logging#4]
Hi. The java action SetRootLevel has the javadoc: FOR DEVELOPMENT PURPOSES ONLY!
But should it?
I think we want Log4j/SLF4J WARN and higher from all loggers to be redirected to a Mendix log node in production too!
It's just strange that it uses the same parameter for the Mendix log node and the log4j logger. We currently pass WARN and an empty string to the action and it will log the warnings to the Mendix log node '' (empty string), but maybe it should be a separate parameter.

Similarly, AddLibraryLogListener does have two separate parameters for that purpose, but it lacks the level parameter. So we get a lot of unwanted INFO from `net.schmizz.sshj`.

**Comment by ArjenLammers** [comment]
hi @basi01 ,
During development of modules like Kafka or SFTP, capturing logging on the root level (even on WARN) generated way too much logging and is quite irrelevant to logging which is usually part of a Mendix application (functional oriented). 
Information added from the main library (like sshj or kafka) already provided a lot more insights.
Collecting all information from WARN and up and redirecting it to the Mendix log would have been a bottleneck for production systems.
